version: '3.8'

services:
  mongo:
    image: mongo:6
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  backend:
    build:
      context: ../back
      dockerfile: Dockerfile
    container_name: backend
    working_dir: /app
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    environment:
      - DB_URL=mongodb://mongo:27017/myapp
    volumes:
      - ../back:/app
      - /app/node_modules
      - ../shared:/app/shared

  frontend:
    build:
      context: ../front
      dockerfile: Dockerfile
    container_name: frontend
    working_dir: /app
    ports:
      - "3001:3001"
    depends_on:
      - backend
    volumes:
      - ../front:/app
      - /app/node_modules
      - ../shared:/app/shared
    command: npm run start

volumes:
  mongo-data:
